### ISSUE TITLE
Do windows line endings on config.txt screw things up?

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-rootfs#10]
A PandA user has a "HOSTNAME = something\r\r\n" in their file, and hostname is not getting set. Are these things related?

**Comment by Araneidae** [comment]
I'm afraid that `\r` is not a recognised character.  They're trying to set `HOSTNAME` to `"something\r\r"`, and this is probably an invalid host name.

Validating `config.txt` is difficult to do at startup: what do we do when it's bad?  And we don't have the option to validate it earlier either.

_maybe_ the `sed` script could be amended to discard `[\r\s\t]*$` as well?
