### ISSUE TITLE
USB port does not work with current rootfs 

### ISSUE THREAD

**Issue by tomtrafford** [PandABlocks/PandABlocks-rootfs#33]
I've noticed that updating the rootfs from 2.0.2 to the most recent version (3.0a3) causes the USB port to stop working. I have changed the version between 3.0a3 and 2.0.2 a few times and I found that the USB port always works on 2.0.2 and never works on 3.0a3.

**Comment by EmilioPeJu** [comment]
It's not a trivial issue, the driver refuse to probe the driver after [this commit](https://github.com/Xilinx/linux-xlnx/commit/d2866e8d3141dedcde8cfc47e3564938145cb46a), my guess is that Vivado needs to be updated to create a device tree providing the attribute "usb-phy". Given this is not a critical issue, I suggest we wait for the project update to 2022 or 2023

**Comment by coretl** [comment]
Who's working on the update to a later vivado? We need to get V3 out the door in June, and the USB needs to be working by then...

**Comment by EmilioPeJu** [comment]
Glenn has a solution to this problem and it's actually in the FPGA repo, it should be ready before the release in June

**Comment by glennchid** [comment]
This is fixed in the PandABlocks-FPGA repo:
https://github.com/PandABlocks/PandABlocks-FPGA/pull/114
